[package]
name = "client"
version = "0.1.0"
authors = ["johnlim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
serde_json = "1.0"
rand = "0.7.2"