[package]
name = "server"
version = "0.1.0"
authors = ["johnlim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
hyper = "0.12"
futures = "0.1"
order = { path = "../lib" }
serde_json = "1.0"